### ISSUE TITLE
Compilation fails when targeting Android 12

### ISSUE THREAD

**Issue by oneeyedraven** [AtomSDK/atomsdk-demo-android#15]
> Task :app:processDebugMainManifest FAILED
AndroidManifest.xml:50:9-65:20 Error:
	android:exported needs to be explicitly specified for element <activity#com.atom.netguard.ActivityMain>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
AndroidManifest.xml:43:9-50:19 Error:
	android:exported needs to be explicitly specified for element <service#de.blinkt.openvpn.core.OpenVPNService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
AndroidManifest.xml:19:9-25:19 Error:
	android:exported needs to be explicitly specified for element <service#com.purevpn.proxy.core.LocalVpnService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
AndroidManifest.xml:71:9-78:19 Error:
	android:exported needs to be explicitly specified for element <service#com.atom.netguard.ServiceSinkhole>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
AndroidManifest.xml:79:9-85:19 Error:
	android:exported needs to be explicitly specified for element <service#com.atom.netguard.ServiceExternal>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
AndroidManifest.xml:16:9-22:19 Error:
	android:exported needs to be explicitly specified for element <service#com.wireguard.android.backend.GoBackend$VpnService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
AndroidManifest.xml:63:9-68:20 Error:
	android:exported needs to be explicitly specified for element <receiver#de.blinkt.openvpn.OnBootReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
AndroidManifest.xml:129:9-135:20 Error:
	android:exported needs to be explicitly specified for element <receiver#com.atom.netguard.ReceiverPackageRemoved>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by atom-sdk** [comment]
@oneeyedraven Please use the updated Atom SDK version 4.3.0. You can follow the updated SDK demo application.
