### ISSUE TITLE
Could not find purevpn-sdk-android.aar (org.bitbucket.purevpn:purevpn-sdk-android:3.3.0).

### ISSUE THREAD

**Issue by muhammedalikocabey** [AtomSDK/atomsdk-demo-android#16]
Execution failed for task ':XXX:compileDevelDebugAidl'.
> Could not resolve all files for configuration ':XXX:develDebugCompileClasspath'.
   > Could not find purevpn-sdk-android.aar (org.bitbucket.purevpn:purevpn-sdk-android:3.3.0).
     Searched in the following locations:
         https://jitpack.io/org/bitbucket/purevpn/purevpn-sdk-android/3.3.0/purevpn-sdk-android-3.3.0.aar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by saidmotya** [comment]
Try to use last version :
 implementation 'org.bitbucket.purevpn:purevpn-sdk-android:4.0.1'
& add in your repositories : 
 maven { url "https://bitbucket.org/purevpn/atom-android-releases/raw/master" }

**Comment by atom-sdk** [comment]
Marking this issue closed, The above-mentioned answer will fix the issue.
