### ISSUE TITLE
how to get Get Subscribed Countries, Get Subscribed Cities etc ?

### ISSUE THREAD

**Issue by mindAndroid** [AtomSDK/atomsdk-demo-android#2]
hi. i have test the demo in details and its look very limited as compare to doc we read. there is number of feture like Get Subscribed Cities, Get Subscribed Countries, but the demo apps return only few server
please update the demo for all feature

**Comment by atom-sdk** [comment]
Hi @mindAndroid,

Sorry for the delayed response.
Please login to your partner panel to get details of Subscribed inventory.

Best Regards
