### ISSUE TITLE
android:exported in SDK 31 and higher !

### ISSUE THREAD

**Issue by saidmotya** [AtomSDK/atomsdk-demo-android#20]
The Apps targeting Android 12 and higher are required to specify an explicit value for android:exported : 

<service#de.blinkt.openvpn.core.OpenVPNService>
<service#com.purevpn.proxy.core.LocalVpnService>
<service#com.atom.netguard.ServiceSinkhole>
<service#com.atom.netguard.ServiceExternal>
<service#com.wireguard.android.backend.GoBackend$VpnService>
<receiver#de.blinkt.openvpn.OnBootReceiver>
<receiver#com.atom.netguard.ReceiverPackageRemoved>
<service#com.wireguard.android.backend.GoBackend$VpnService>

**Comment by LOGSOU** [comment]
up

**Comment by atom-sdk** [comment]
Hi,

@saidmotya @LOGSOU You can use the updated Atom SDK version 4.3.0. Please follow the Demo Sample App for integration.
