### ISSUE TITLE
The SDK very large 47,6 MB (91,5%) of my empty project !!

### ISSUE THREAD

**Issue by saidmotya** [AtomSDK/atomsdk-demo-android#21]
I created an empty project and I added your SDK, than I create a simple initialize of code and make a successfully connection to VPN, but after building .aab the app is very large, that yours library is so big : see the screenshot 

![image](https://user-images.githubusercontent.com/15313536/193258953-05208156-788e-40e5-b4c7-5b756b563402.png)
Why ?

**Comment by atom-sdk** [comment]
You can follow Atom SDK demo Readme.md to use .aab app bundle. These are architecture based libraries for VPN protocols. Configuring app bundle will help you reduce your app file size. Please follow the below link

https://github.com/AtomSDK/atomsdk-demo-android#resolve-issues-when-building-an-android-app-bundle
