### ISSUE TITLE
Extra config

### ISSUE THREAD

**Issue by rafaeliga** [AtomSDK/atomsdk-demo-android#26]
Hello there!

Im integrating the SDK into a flutter app.

When building, I got this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/core_release.kotlin_module'.
```

To fix the error I had to add this extra config on app/build.gradle:

```
android {
   packagingOptions {
      pickFirst 'META-INF/core_release.kotlin_module'
  }
}
```

(exclude works instead of pickFirst too)

Is there something specific in a flutter app that needs that?

Thanks,

**Comment by atom-sdk** [comment]
The exclusion guide has been provided in demo application in case of any duplicate module, Closing this issue.
