### ISSUE TITLE
Errors when Merging this project in flutter application

### ISSUE THREAD

**Issue by racilh** [AtomSDK/atomsdk-demo-android#36]
I'm currently encountering challenges while integrating a android Atom SDK into my Flutter application. The issues primarily revolve around merge errors between libraries such as the flutter openvpn's manifest file , authentication problems with JitPack getting 401  Unauthorized when building, altho i used the authToken. In order to better understand the integration process and resolve the issues efficiently, could you please provide me with a Flutter demo or atleast the manifest and build.gradles that demonstrates the correct implementation of the AtomSDK? Your assistance in this matter would be greatly appreciated.

Error for jitpack:

 Execution failed for task ':app:checkDebugAarMetadata'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform AtomSdk-4.4.2.aar (org.bitbucket.purevpn.purevpn-sdk-android:AtomSdk:4.4.2) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not download AtomSdk-4.4.2.aar (org.bitbucket.purevpn.purevpn-sdk-android:AtomSdk:4.4.2)
         > Could not get resource 'https://jitpack.io/org/bitbucket/purevpn/purevpn-sdk-android/AtomSdk/4.4.2/AtomSdk-4.4.2.aar'.
            > Could not HEAD 'https://jitpack.io/org/bitbucket/purevpn/purevpn-sdk-android/AtomSdk/4.4.2/AtomSdk-4.4.2.aar'. Received status code 401 from server: Unauthorized

 Errors in Manifest:

Attribute service#de.blinkt.openvpn.core.OpenVPNService@exported value=(false) from [org.bitbucket.purevpn.purevpn-sdk-android:AtomSdk:4.4.2] AndroidManifest.xml:53:13-37
	is also present at [com.github.nizwar:openvpn_library:5f06771b85] AndroidManifest.xml:24:13-36 value=(true).
	Suggestion: add 'tools:replace="android:exported"' to <service> element at AndroidManifest.xml:50:9-59:19 to override.

**Comment by atom-sdk** [comment]
Hi @racilh,
It looks that you have declared OpenVPNService in your Android code manifest again. You don't need to mention this in your android flutter code. OpenVPNService is already declared in Atom SDK. If this is correct, Remove this from your code & try to build your code again.
