### ISSUE TITLE
Vpn disconnect when start new activity with finish();

### ISSUE THREAD

**Issue by saidmotya** [AtomSDK/atomsdk-demo-android#8]
Hello team Atom ! after install your SDK in my application i faced some issue, I make VPN connected successfully in MainActivity and when start the second Activity VPN disconnect and notification disappear, after trying to figure why ! I think when destroy the Activity or add some flag to clear to start the second activity, VPN also disconnect, How i can use the VPN without disconnect in case start new activity or new fragment in onResume method. thank you

**Comment by PratikFagadiya** [comment]
hey @saidmotya have you found any solution ? I'm facing same issue currently.
